/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import animales.AnimalDomestico;
import animales.AnimalSalvaje;
import zoologico.DepartamentoLogistica;


/**
 *
 * @author Valentina
 */
public class VentanaAnimal extends javax.swing.JFrame {
    
    
    public VentanaAnimal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonAnimalSalvaje = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextNombreAnimalSalvaje = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextEspecieSalvaje = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextCodigoSalvaje = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextPeligrosidadSalvaje = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonAnimalDomestico = new javax.swing.JRadioButton();
        jTextUsoDomestico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextNombreAnimalDomestico = new javax.swing.JTextField();
        jTextEspecieDomestico = new javax.swing.JTextField();
        jTextCodigoDomestico = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jBAgregarAnimal = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Animal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jRadioButtonAnimalSalvaje.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonAnimalSalvaje);
        jRadioButtonAnimalSalvaje.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jRadioButtonAnimalSalvaje.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonAnimalSalvaje.setText("Animal Salvaje");
        jRadioButtonAnimalSalvaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAnimalSalvajeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre del animal");

        jTextNombreAnimalSalvaje.setEditable(false);
        jTextNombreAnimalSalvaje.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextNombreAnimalSalvaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreAnimalSalvajeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Especie");

        jTextEspecieSalvaje.setEditable(false);
        jTextEspecieSalvaje.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextEspecieSalvaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEspecieSalvajeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Código");

        jTextCodigoSalvaje.setEditable(false);
        jTextCodigoSalvaje.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextCodigoSalvaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoSalvajeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Peligrosidad");

        jTextPeligrosidadSalvaje.setEditable(false);
        jTextPeligrosidadSalvaje.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextPeligrosidadSalvaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPeligrosidadSalvajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonAnimalSalvaje, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNombreAnimalSalvaje, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextEspecieSalvaje, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCodigoSalvaje, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPeligrosidadSalvaje, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonAnimalSalvaje, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextNombreAnimalSalvaje, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextEspecieSalvaje, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextCodigoSalvaje, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextPeligrosidadSalvaje, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jRadioButtonAnimalDomestico.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonAnimalDomestico);
        jRadioButtonAnimalDomestico.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jRadioButtonAnimalDomestico.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonAnimalDomestico.setText("Animal Doméstico");
        jRadioButtonAnimalDomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAnimalDomesticoActionPerformed(evt);
            }
        });

        jTextUsoDomestico.setEditable(false);
        jTextUsoDomestico.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextUsoDomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsoDomesticoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Uso");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Código");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Especie");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre del animal");

        jTextNombreAnimalDomestico.setEditable(false);
        jTextNombreAnimalDomestico.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextNombreAnimalDomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreAnimalDomesticoActionPerformed(evt);
            }
        });

        jTextEspecieDomestico.setEditable(false);
        jTextEspecieDomestico.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextEspecieDomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEspecieDomesticoActionPerformed(evt);
            }
        });

        jTextCodigoDomestico.setEditable(false);
        jTextCodigoDomestico.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextCodigoDomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoDomesticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonAnimalDomestico)
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextCodigoDomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextUsoDomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextEspecieDomestico, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                .addComponent(jTextNombreAnimalDomestico, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonAnimalDomestico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextNombreAnimalDomestico, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextEspecieDomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextCodigoDomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextUsoDomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jBAgregarAnimal.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jBAgregarAnimal.setText("AGREGAR");
        jBAgregarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarAnimalActionPerformed(evt);
            }
        });

        jBAtras.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jBAtras.setText("Atras");
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAgregarAnimal)
                .addGap(182, 182, 182)
                .addComponent(jBAtras)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregarAnimal)
                    .addComponent(jBAtras))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreAnimalSalvajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreAnimalSalvajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreAnimalSalvajeActionPerformed

    private void jTextEspecieSalvajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEspecieSalvajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEspecieSalvajeActionPerformed

    private void jTextCodigoSalvajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoSalvajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigoSalvajeActionPerformed

    private void jTextPeligrosidadSalvajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPeligrosidadSalvajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPeligrosidadSalvajeActionPerformed

    private void jTextUsoDomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsoDomesticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsoDomesticoActionPerformed

    private void jTextNombreAnimalDomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreAnimalDomesticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreAnimalDomesticoActionPerformed

    private void jTextEspecieDomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEspecieDomesticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEspecieDomesticoActionPerformed

    private void jTextCodigoDomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoDomesticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCodigoDomesticoActionPerformed

    private void jRadioButtonAnimalSalvajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAnimalSalvajeActionPerformed
        hacerEditablePorTipo("Salvaje");
    }//GEN-LAST:event_jRadioButtonAnimalSalvajeActionPerformed

    private void jRadioButtonAnimalDomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAnimalDomesticoActionPerformed
        hacerEditablePorTipo("Domestico");
    }//GEN-LAST:event_jRadioButtonAnimalDomesticoActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        Index index = new Index();
        index.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBAtrasActionPerformed

    private void jBAgregarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarAnimalActionPerformed
        if(jRadioButtonAnimalDomestico.isSelected()){
            AnimalDomestico animalDomestico = new AnimalDomestico(jTextUsoDomestico.getText(), Integer.parseInt(jTextCodigoDomestico.getText()), jTextNombreAnimalDomestico.getText(), jTextEspecieDomestico.getText());
            try {
                DepartamentoLogistica.ingresarAnimalDomestico(animalDomestico);
            } catch (IOException ex) {
                Logger.getLogger(VentanaAnimal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(jRadioButtonAnimalSalvaje.isSelected()){
            AnimalSalvaje animalSalvaje = new AnimalSalvaje(jTextPeligrosidadSalvaje.getText(), Integer.parseInt(jTextCodigoSalvaje.getText()), jTextNombreAnimalSalvaje.getText(), jTextEspecieSalvaje.getText());
            try {
                DepartamentoLogistica.ingresarAnimalSalvaje(animalSalvaje);
            } catch (IOException ex) {
                Logger.getLogger(VentanaAnimal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        hacerEditablePorTipo("Ninguno");
    }//GEN-LAST:event_jBAgregarAnimalActionPerformed

    private void hacerEditablePorTipo(String tipo){
        if("Salvaje".equalsIgnoreCase(tipo)){
            jTextNombreAnimalSalvaje.setEditable(true);
            jTextEspecieSalvaje.setEditable(true);
            jTextCodigoSalvaje.setEditable(true);
            jTextPeligrosidadSalvaje.setEditable(true);
            jTextNombreAnimalDomestico.setEditable(false);
            jTextEspecieDomestico.setEditable(false);
            jTextCodigoDomestico.setEditable(false);
            jTextUsoDomestico.setEditable(false);
        }
        else if("Domestico".equalsIgnoreCase(tipo)) {
            jTextNombreAnimalDomestico.setEditable(true);
            jTextEspecieDomestico.setEditable(true);
            jTextCodigoDomestico.setEditable(true);
            jTextUsoDomestico.setEditable(true);
            jTextNombreAnimalSalvaje.setEditable(false);
            jTextEspecieSalvaje.setEditable(false);
            jTextCodigoSalvaje.setEditable(false);
            jTextPeligrosidadSalvaje.setEditable(false);
        }
        else if("Ninguno".equalsIgnoreCase(tipo)){
            jTextNombreAnimalDomestico.setEditable(false);
            jTextNombreAnimalDomestico.setText("");
            
            jTextEspecieDomestico.setEditable(false);
            jTextEspecieDomestico.setText("");
            
            jTextCodigoDomestico.setEditable(false);
            jTextCodigoDomestico.setText("");
            
            jTextUsoDomestico.setEditable(false);
            jTextUsoDomestico.setText("");
            
            jTextNombreAnimalSalvaje.setEditable(false);
            jTextNombreAnimalSalvaje.setText("");
            
            jTextEspecieSalvaje.setEditable(false);
            jTextEspecieSalvaje.setText("");
            
            jTextCodigoSalvaje.setEditable(false);
            jTextCodigoSalvaje.setText("");
            
            jTextPeligrosidadSalvaje.setEditable(false);
            jTextPeligrosidadSalvaje.setText("");
            
            buttonGroup1.clearSelection();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAgregarAnimal;
    private javax.swing.JButton jBAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonAnimalDomestico;
    private javax.swing.JRadioButton jRadioButtonAnimalSalvaje;
    private javax.swing.JTextField jTextCodigoDomestico;
    private javax.swing.JTextField jTextCodigoSalvaje;
    private javax.swing.JTextField jTextEspecieDomestico;
    private javax.swing.JTextField jTextEspecieSalvaje;
    private javax.swing.JTextField jTextNombreAnimalDomestico;
    private javax.swing.JTextField jTextNombreAnimalSalvaje;
    private javax.swing.JTextField jTextPeligrosidadSalvaje;
    private javax.swing.JTextField jTextUsoDomestico;
    // End of variables declaration//GEN-END:variables
}
